---
title: "주제도 제작의 절차와 지도 디자인"
author: Sang-Il Lee
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
editor_options: 
  chunk_output_type: console
---

## 주제도 제작의 절차

## 지도 디자인

### 행정구역

#### 데이터 준비

- 필수적인 패키지 불러오기

```{r}
library(tidyverse) 
library(readxl) 
library(sf) 
library(tmap)
library(tmaptools)
library(ggspatial)
```

- 형상 데이터 불러오기

```{r}
#| results: hide
sido <- read_sf("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2020_2Q/SIDO_2020_2Q_GEN_0050.shp", options = "ENCODING=CP949")
sigun1 <- read_sf("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2020_2Q/SIGUN1_2020_2Q_GEN_0050.shp", options = "ENCODING=CP949")
sigungu1 <- read_sf("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2020_2Q/SIGUNGU1_2020_2Q_GEN_0050.shp", options = "ENCODING=CP949")
emd <- read_sf("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2020_2Q/EMD_2020_2Q_GEN_0050.shp", options = "ENCODING=CP949")
sido_polyline <- read_sf("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2020_2Q/SIDO_Polyline_2020_2Q_GEN_0050.shp", options = "ENCODING=CP949")
bbox_ulleung <- read_sf("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2020_2Q/BBOX_Ulleung_2020_2Q_GEN_0050.shp", options = "ENCODING=CP949")
bbox_seohae <- read_sf("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2020_2Q/BBOX_Seohae3_2020_2Q_GEN_0050.shp", options = "ENCODING=CP949")
seoul_gu <- read_sf(
  "D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2021_4Q/SEOUL_GU_2021_4Q.shp", options = "ENCODING=CP949"
  ) 
seoul_sido <- read_sf(
  "D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2021_4Q/SEOUL_SIDO_2021_4Q.shp", options = "ENCODING=CP949"
  )
```

#### 시도 경계 지도

- [**tmap**](https://r-tmap.github.io/tmap/index.html): 지도 제작

```{r}
#| fig-height: 12
#| fig-width: 9.047974
#| fig-dpi: 600

my_map <- tm_shape(sido) + tm_polygons() +
  tm_shape(sido_polyline) + tm_lines(col = "black", lwd = 1.75) +
  tm_shape(bbox_ulleung) + tm_lines() +
  tm_shape(bbox_seohae) + tm_lines() +
  tm_layout(inner.margins = c(0.02, 0.02, 0.02, 0.03)) +
  tm_scalebar(breaks = seq(0, 200, 50), text.size = 0.6, color.dark = "gray60", 
             position = c(0.52, 0.03), allow_clipping = TRUE)
my_map 
```

- [**tmap**](https://r-tmap.github.io/tmap/index.html): 저장

```{r}
#| eval: false
#| echo: false
my.ratio <- get_asp_ratio(my_map)

my.title <- "9-2-01-1 시도 경계 tmap"
my.file.name <- paste0("D:/My Cartography/지도제작/", my.title, ".png")
tmap_save(
  my_map, filename = my.file.name,  height = 12, width = my.ratio*12, dpi = 600)
```

- [**ggplot2**](https://ggplot2.tidyverse.org/): 지도 제작

```{r}
#| fig-height: 12
#| fig-width: 9.047974
#| fig-dpi: 600
#| eval: false

my_map <- ggplot() +
  geom_sf(data = sido) +
  geom_sf(data = sido_polyline) +
  geom_sf(data = bbox_ulleung) +
  geom_sf(data = bbox_seohae) +
  annotation_scale(location = "br", bar_cols = c("gray40", "white"), width_hint = 0.4) +
  theme_void() +
  theme(
    panel.background = element_rect(color = "gray20", fill = "white", linewidth = 1),
    plot.margin = margin(5, 5, 5, 5)
  )
my_map
```

- [**ggplot2**](https://ggplot2.tidyverse.org/): 저장

```{r}
#| echo: false
#| eval: false

my.title <- "9-2-01-2 시도 경계 ggplot"
my.file.name <- paste0("D:/My Cartography/지도제작/", my.title, ".png")
ggsave(my_map, filename = my.file.name, height = 12, width = 9.047974, dpi = 600)
```

#### 시군구 경계 지도

- 지도 제작

```{r}
#| fig-height: 12
#| fig-width: 8.961803
#| fig-dpi: 600

my_map <- tm_shape(sigungu1) + tm_polygons() +
  tm_shape(sido_polyline) + tm_lines(col = "black", lwd = 1.75) +
  tm_shape(bbox_ulleung) + tm_lines() +
  tm_shape(bbox_seohae) + tm_lines() +
  tm_scalebar(breaks = seq(0, 200, 50), text.size = 0.6, color.dark = "gray60", 
             position = c(0.52, 0.03), allow_clipping = TRUE)
  tm_layout(inner.margins = c(0.02, 0.02, 0.02, 0.03))
my_map
```

- 저장

```{r}
#| echo: false
#| eval: false

my.ratio <- get_asp_ratio(my_map)

my.title <- "9-2-02-1 시군도 경계 tmap"
my.file.name <- paste0("D:/My Cartography/지도제작/", my.title, ".png")
tmap_save(
  my_map, filename = my.file.name,  height = 12, width = my.ratio*12, dpi = 600)
```

#### 읍면동 경계 지도

- 지도 제작

```{r}
#| fig-height: 12
#| fig-width: 9.047974
#| fig-dpi: 600

my_map <- tm_shape(emd) + tm_polygons() +
  tm_shape(sido_polyline) + tm_lines(col = "black", lwd = 1.75) +
  tm_shape(bbox_ulleung) + tm_lines() +
  tm_shape(bbox_seohae) + tm_lines() +
  tm_scalebar(breaks = seq(0, 200, 50), text.size = 0.6, color.dark = "gray60", 
             position = c(0.52, 0.03), allow_clipping = TRUE) +
  tm_layout(inner.margins = c(0.02, 0.02, 0.02, 0.03))
my_map
```

- 저장

```{r}
#| echo: false
#| eval: false

my.ratio <- get_asp_ratio(my_map)

my.title <- "9-2-03-1 읍면동 경계 tmap"
my.file.name <- paste0("D:/My Cartography/지도제작/", my.title, ".png")
tmap_save(
  my_map, filename = my.file.name,  height = 12, width = my.ratio*12, dpi = 600)
```

### 지도 디자인: 예시

#### 데이터 준비

- 형상 데이터 불러오기: 읍면동 변동을 반영한 데이터

```{r}
emd_adj <- read_sf("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/3 Generalization/2020_Census_Adj/EMD_2020_Census_GEN_0020.shp", options = "ENCODING=CP949")
```

- 속성 데이터 불러오기: 읍면동 변동을 반영한 데이터

```{r}
pop_adj <- read_excel("D:/My R/Korea Census Data Manipulation/1 Population Basic/DM_ADJ_Census_2020.xlsx", sheet = 1)
```

- 결합

```{r}
emd_adj <- emd_adj |> 
  mutate(EMD_ID = as.numeric(EMD_ID))
emd_adj_data <- emd_adj |> 
  left_join(pop_adj, join_by(EMD_ID == Code)) |> 
  mutate(
    pop_t = ifelse(is.na(pop_t), 0, pop_t)
  )
```

- 인구밀도 계산

```{r}
emd_adj_data <- emd_adj_data |>
  mutate(
     area = geometry |> st_area() |> as.numeric()/1000000,
     pop_den = pop_t / area
  )
```

- [**tmap**](https://r-tmap.github.io/tmap/index.html): 지도 제작

```{r}
#| fig-height: 12
#| fig-width: 8.882838
#| fig-dpi: 600

bbox_ulleung_polygon <- bbox_ulleung |> 
  st_cast("POLYGON")

my_map <- tm_graticules(col = "white", x = seq(126, 130, 1), y = seq(33, 39, 1), labels.size = 0.75) +
  tm_shape(bbox_ulleung_polygon) + tm_fill(fill = "gray90") +
  tm_shape(emd_adj_data, is.main = TRUE) +
  tm_polygons(
    fill = "pop_den", col = NULL,
    fill.scale = tm_scale(
      breaks = c(0, 50, 250, 500, 1000, 5000, 10000, Inf),
      labels = c("0 - 50", "50 - 250", "250 - 500", "500 - 1,000", 
                 "1,000 - 5,000", "5,000 - 10,000", "10,000+"),
      values = "brewer.yl_gn_bu"
    ),
    fill.legend = tm_legend(
      title = expression("People/km"^2), 
      position = tm_pos_in(0.75, 0.28),
      title.size = 1.2, text.size = 1
    )
  ) +
  tm_shape(sigungu1) + tm_borders() +
  tm_shape(sido_polyline) + tm_lines(col = "black", lwd = 1.75) +
  tm_shape(bbox_seohae) + tm_borders() +
  tm_shape(bbox_ulleung_polygon) + tm_borders() +
  tm_title_in("Population Distribution, 2020", size = 2) +
  tm_layout(bg.color = "gray90", inner.margins = c(0.05, 0.09, 0.05, 0.05)) +
  tm_scalebar(breaks = seq(0, 200, 50), text.size = 0.6, color.dark = "gray60", 
             position = c(0.52, 0.03), allow_clipping = TRUE) +
  tm_credits("SANG-IL LEE, Geography Education at SNU", size = 0.7, position = c(0.025, 0.02))
my_map
```

- [**tmap**](https://r-tmap.github.io/tmap/index.html): 지도 저장

```{r}
#| echo: false
#| eval: false

my.ratio <- get_asp_ratio(my_map)

my.title <- "9-2-04-1 인구 밀도 지도 tmap"
my.file.name <- paste0("D:/My Cartography/지도제작/", my.title, ".png")
tmap_save(
  my_map, filename = my.file.name,  height = 12, width = my.ratio*12, dpi = 600)
```

- [**ggplot2**](https://ggplot2.tidyverse.org/): 지도 제작

```{r}
#| fig-height: 12
#| fig-width: 8.9538
#| fig-dpi: 600

emd_adj_data_1 <- emd_adj_data |> 
  mutate(
    pop_den = cut(pop_den, 
                  breaks = c(-Inf, 50, 250, 500, 1000, 5000, 10000, Inf),
                  labels = c("0 to 50", "50 to 250", "250 to 500", "500 to 1,000", 
                             "1,000 to 5,000", "5,000 to 10,000", "10,000 or more"))
  )

my_map <- ggplot() + 
  geom_sf(data = bbox_ulleung_polygon, fill = "gray92", lwd = 0.1) +
  geom_sf(
    data = emd_adj_data_1, aes(fill = pop_den), color = NA) +
  geom_sf(data = sigungu1, fill = NA) +
  geom_sf(data = sido_polyline) +
  geom_sf(data = bbox_seohae, lwd = 0.1) +
  scale_fill_brewer(palette = "YlGnBu", name = expression("People/km"^2)) +
  annotate("text", x = -Inf, y = Inf, hjust = -0.05, vjust = 2, size = 7.5,   
           label = "Population Distribution, 2020") +
  annotate("text", x = -Inf, y = -Inf, hjust = -0.1, vjust = -1.5, size = 3.5,   
           label = "SANG-IL LEE, Geography Education at SNU") +
  annotation_scale(location = "br", bar_cols = c("gray40", "white"), 
                   width_hint = 0.4, pad_y = unit(0.5, "cm")) +
  theme(
    legend.position = "inside",
    legend.position.inside = c(0.85, 0.15),
    legend.background = element_rect(fill = "white")) 
my_map
```

- [**ggplot2**](https://ggplot2.tidyverse.org/): 저장

```{r}
#| echo: false
#| eval: false

my.title <- "9-2-04-2 인구 밀도 지도 ggplot"
my.file.name <- paste0("D:/My Cartography/지도제작/", my.title, ".png")
ggsave(my_map, filename = my.file.name, height = 12, width = 9, dpi = 600)
```
